"""Schemas package for type-safe inter-agent communication."""

from .messages import (
    UserQuery,
    PlannerOutput,
    LegalSource,
    ResearchOutput,
    ReasoningOutput,
    ValidationIssue,
    ValidationOutput,
    SynthesizerOutput,
    RefusalOutput,
    AuditLogEntry,
)

# Authentication schemas
from .lawyers import (
    LawyerBase,
    LawyerRegister,
    LawyerLogin,
    LawyerResponse,
    LawyerProfileResponse,
    PasswordChange,
    PasswordResetRequest,
    PasswordReset,
    EmailVerification,
    MFASetupResponse,
    MFAEnable,
    MFAVerify,
    SessionResponse,
)

from .admin import (
    AdminBase,
    AdminRegister,
    AdminLogin,
    AdminResponse,
    AdminUpdate,
    AdminPasswordChange,
    AdminMFASetupResponse,
    AdminMFAEnable,
    AdminSessionResponse,
    AdminListResponse,
    AdminProfile,
)

from .auth import (
    Token,
    TokenRefresh,
    TokenRefreshResponse,
    TokenResponse,
    LoginResponse,
    MFARequiredResponse,
    LogoutResponse,
    MessageResponse,
    ErrorResponse,
    PasswordResetEmailSentResponse,
    EmailVerificationSentResponse,
    RegistrationResponse,
    UserProfile,
    UserRegister,
    UserLogin,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    EmailVerification,
    SessionInfo,
    ActiveSessionsResponse,
    MFASetupResponse,
    MFAEnable,
    MFAVerify,
    MFADisable,
    MFAStatus,
)

__all__ = [
    # Message schemas
    "UserQuery",
    "PlannerOutput",
    "LegalSource",
    "ResearchOutput",
    "ReasoningOutput",
    "ValidationIssue",
    "ValidationOutput",
    "SynthesizerOutput",
    "RefusalOutput",
    "AuditLogEntry",
    
    # Lawyer schemas
    "LawyerBase",
    "LawyerRegister",
    "LawyerLogin",
    "LawyerResponse",
    "LawyerProfileResponse",
    "PasswordChange",
    "PasswordResetRequest",
    "PasswordReset",
    "EmailVerification",
    "MFASetupResponse",
    "MFAEnable",
    "MFAVerify",
    "SessionResponse",
    
    # Admin schemas
    "AdminBase",
    "AdminRegister",
    "AdminLogin",
    "AdminResponse",
    "AdminUpdate",
    "AdminPasswordChange",
    "AdminMFASetupResponse",
    "AdminMFAEnable",
    "AdminSessionResponse",
    "AdminListResponse",
    "AdminProfile",
    
    # Auth schemas
    "Token",
    "TokenRefresh",
    "TokenRefreshResponse",
    "TokenResponse",
    "LoginResponse",
    "MFARequiredResponse",
    "LogoutResponse",
    "MessageResponse",
    "ErrorResponse",
    "PasswordResetEmailSentResponse",
    "EmailVerificationSentResponse",
    "RegistrationResponse",
    "UserProfile",
    "UserRegister",
    "UserLogin",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "EmailVerification",
    "SessionInfo",
    "ActiveSessionsResponse",
    "MFASetupResponse",
    "MFAEnable",
    "MFAVerify",
    "MFADisable",
    "MFAStatus",
]
