"""
Synthesizer Agent

Role: Presentation ONLY - formats final response.

This agent:
- Formats the validated reasoning for user presentation
- Adds proper citations
- Adds confidence notes
- Adds legal disclaimers
- Does NO reasoning
- Does NO retrieval
- Does NO validation
- Makes NO decisions

This is purely a presentation layer.
"""

from typing import Tuple
from langchain_core.runnables import Runnable, RunnableLambda

from schemas.messages import (
    ResearchOutput,
    ReasoningOutput,
    ValidationOutput,
    SynthesizerOutput,
    RefusalOutput
)


# Standard legal disclaimer
LEGAL_DISCLAIMER = """
IMPORTANT LEGAL NOTICE:

This response is generated by an AI system based solely on the legal sources 
retrieved from the Sri Lankan legal database (MCP). This is NOT legal advice.

- This analysis is for informational purposes only
- It should not be relied upon as legal counsel
- Consult a qualified attorney for specific legal guidance
- The AI system may have limitations in legal interpretation
- Laws may have been updated since the sources were last retrieved

Users should verify all legal citations with official legal texts.
"""


def create_synthesizer_runnable() -> Runnable:
    """
    Create the Synthesizer agent as a LangChain Runnable.

    This agent formats validated reasoning for user presentation.
    It performs NO reasoning, only formatting.

    Returns:
        Runnable that takes (ResearchOutput, ReasoningOutput, ValidationOutput) 
        and returns SynthesizerOutput
    """

    def synthesize(
        inputs: Tuple[ResearchOutput, ReasoningOutput, ValidationOutput]
    ) -> SynthesizerOutput:
        """
        Format the final response for user presentation.

        Args:
            inputs: Tuple of (ResearchOutput, ReasoningOutput, ValidationOutput)

        Returns:
            SynthesizerOutput with formatted response
        """
        research_output, reasoning_output, validation_output = inputs

        # Format the main response
        response_parts = []

        # Add header
        response_parts.append("# Legal Analysis\n")

        # Add analysis
        response_parts.append("## Analysis\n")
        response_parts.append(reasoning_output.analysis)
        response_parts.append("\n")

        # Add limitations
        response_parts.append("## Limitations\n")
        response_parts.append(reasoning_output.limitations)
        response_parts.append("\n")

        # Add legal sources used
        response_parts.append("## Legal Sources\n")
        if research_output.sources:
            for idx, source in enumerate(research_output.sources, 1):
                response_parts.append(
                    f"{idx}. **{source.law_name}**, Section {source.section}\n"
                    f"   > {source.text[:200]}{'...' if len(source.text) > 200 else ''}\n"
                )
        else:
            response_parts.append(
                "No legal sources were available for this query.\n")
        response_parts.append("\n")

        # Add validation notes if there are warnings
        if validation_output.issues:
            response_parts.append("## Validation Notes\n")
            for issue in validation_output.issues:
                emoji = "🔴" if issue.severity == "critical" else "⚠️" if issue.severity == "warning" else "ℹ️"
                response_parts.append(
                    f"{emoji} **{issue.type}**: {issue.description}\n")
            response_parts.append("\n")

        # Combine into final response
        response = "".join(response_parts)

        # Format confidence note
        confidence_note = format_confidence_note(
            validation_output.confidence,
            validation_output.all_citations_verified,
            validation_output.no_hallucination_detected
        )

        # Prepare metadata
        metadata = {
            "retrieval_timestamp": research_output.retrieval_timestamp,
            "sources_count": len(research_output.sources),
            "citations_count": len(reasoning_output.citations_used),
            "validation_status": validation_output.status,
            "reasoning_confidence": reasoning_output.confidence,
            "validation_confidence": validation_output.confidence
        }

        return SynthesizerOutput(
            response=response,
            citations=research_output.sources,
            confidence_note=confidence_note,
            disclaimer=LEGAL_DISCLAIMER,
            metadata=metadata
        )

    return RunnableLambda(synthesize)


def create_refusal_synthesizer() -> Runnable:
    """
    Create a synthesizer for validation failures.

    When validation fails, this generates an appropriate refusal message.

    Returns:
        Runnable that takes ValidationOutput and returns RefusalOutput
    """

    def synthesize_refusal(validation_output: ValidationOutput) -> RefusalOutput:
        """
        Generate a refusal message when validation fails.

        Args:
            validation_output: The failed validation output

        Returns:
            RefusalOutput with explanation
        """
        # Categorize issues
        critical_issues = [
            i for i in validation_output.issues if i.severity == "critical"]

        # Generate reason
        reason_parts = [
            "The system cannot provide a legal analysis for this query due to the following issues:\n"
        ]

        for issue in critical_issues:
            reason_parts.append(f"• {issue.description}\n")

        reason = "".join(reason_parts)

        # Generate suggestions
        suggestions = generate_refusal_suggestions(validation_output.issues)

        return RefusalOutput(
            reason=reason,
            issues=validation_output.issues,
            suggestions=suggestions
        )

    return RunnableLambda(synthesize_refusal)


def format_confidence_note(
    confidence: float,
    all_citations_verified: bool,
    no_hallucination_detected: bool
) -> str:
    """
    Generate a user-friendly confidence note.

    Args:
        confidence: Confidence score (0.0 to 1.0)
        all_citations_verified: Whether all citations were verified
        no_hallucination_detected: Whether hallucinations were detected

    Returns:
        Formatted confidence note
    """
    notes = []

    # Overall confidence
    if confidence >= 0.8:
        notes.append("✅ High confidence in this analysis.")
    elif confidence >= 0.5:
        notes.append("⚠️ Moderate confidence in this analysis.")
    else:
        notes.append("🔴 Low confidence in this analysis.")

    # Citation verification
    if all_citations_verified:
        notes.append(
            "✅ All citations have been verified against legal sources.")
    else:
        notes.append("⚠️ Some citations could not be verified.")

    # Hallucination detection
    if no_hallucination_detected:
        notes.append("✅ No external legal knowledge was used.")
    else:
        notes.append("🔴 Potential use of external legal knowledge detected.")

    return "\n".join(notes)


def generate_refusal_suggestions(issues) -> str:
    """
    Generate suggestions for user when system refuses to answer.

    Args:
        issues: List of ValidationIssue objects

    Returns:
        Suggestions text
    """
    suggestions = []

    # Check for common issue types
    issue_types = {issue.type for issue in issues}

    if "missing_sources" in issue_types:
        suggestions.append(
            "• Try rephrasing your question to be more specific about "
            "the legal topic or statute you're asking about."
        )

    if "hallucination" in issue_types:
        suggestions.append(
            "• The system detected content that may not be from legal sources. "
            "This typically indicates the query requires legal knowledge not "
            "available in the database."
        )

    if "missing_citation" in issue_types:
        suggestions.append(
            "• The analysis lacks proper citations. Try asking about a specific "
            "law or legal provision."
        )

    if not suggestions:
        suggestions.append(
            "• Please rephrase your question or consult with a legal professional."
        )

    return "\n".join(suggestions)


def get_synthesizer_agent() -> Runnable:
    """
    Get the default synthesizer agent.

    Returns:
        Synthesizer agent runnable
    """
    return create_synthesizer_runnable()


def get_refusal_agent() -> Runnable:
    """
    Get the refusal synthesizer agent.

    Returns:
        Refusal synthesizer runnable
    """
    return create_refusal_synthesizer()
